name: ci

on:
  push:
    branches:
      - master
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version:
          - 11
          - 17
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Install
        run: mvn install -B -DskipTests
      - name: Run Tests
        run: mvn -B test
